-- Matches bookings table from migrations (PRD 5.3 / 2.12).
CREATE TABLE bookings (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    confirmation_code TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'confirmed', 'received', 'completed', 'cancelled')),
    service_type TEXT NOT NULL CHECK (service_type IN ('standard', 'express', 'door_to_door')),
    destination_id TEXT NOT NULL,
    recipient_id TEXT REFERENCES recipients(id),
    scheduled_date TEXT NOT NULL,
    time_slot TEXT NOT NULL CHECK (time_slot IN ('morning', 'afternoon', 'evening')),
    special_instructions TEXT,
    weight_lbs REAL NOT NULL DEFAULT 0 CHECK (weight_lbs >= 0),
    length_in REAL NOT NULL DEFAULT 0 CHECK (length_in >= 0),
    width_in REAL NOT NULL DEFAULT 0 CHECK (width_in >= 0),
    height_in REAL NOT NULL DEFAULT 0 CHECK (height_in >= 0),
    value_usd REAL NOT NULL DEFAULT 0 CHECK (value_usd >= 0),
    add_insurance INTEGER NOT NULL DEFAULT 0 CHECK (add_insurance IN (0, 1)),
    subtotal REAL NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount REAL NOT NULL DEFAULT 0 CHECK (discount >= 0),
    insurance REAL NOT NULL DEFAULT 0 CHECK (insurance >= 0),
    total REAL NOT NULL DEFAULT 0 CHECK (total >= 0),
    payment_status TEXT CHECK (payment_status IS NULL OR payment_status IN ('pending', 'paid', 'failed', 'refunded')),
    stripe_payment_intent_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
